### ISSUE TITLE
School Selector

### ISSUE THREAD

**Issue by t0rre** [t0rre/timetable#1]
A school selector needs to be implemented, currently only Kattegattgymnasiet, Halmstad is supported.
@aj0er might be interested?

**Comment by aj0er** [comment]
I will look into this!

**Comment by t0rre** [comment]
> 
> 
> I will look into this!

Thanks!
Do you want me to add you as an collaborator on this repo?

**Comment by aj0er** [comment]
You sure can.

**Comment by t0rre** [comment]
I added a school viewer, which shows the available units/schools in the supplied domain. Though it is not a school selector, but that might be hard to add under my current view that no external files should be needed. Copy the right unitGUID, and add it into the `defaultUnit` variable, or make a batch file to invoke the script with all the arguments, eg `./timetable.py -g <UNIT_GUID> -i <ID> -d <DOMAIN>`
